/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiImportRouteImport } from './routes/api/import'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as ApiWorkersProcessBatchRouteImport } from './routes/api/workers/process-batch'
import { Route as ApiJobsIdRouteImport } from './routes/api/jobs/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportRoute = ApiImportRouteImport.update({
  id: '/api/import',
  path: '/api/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiWorkersProcessBatchRoute = ApiWorkersProcessBatchRouteImport.update({
  id: '/api/workers/process-batch',
  path: '/api/workers/process-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsIdRoute = ApiJobsIdRouteImport.update({
  id: '/api/jobs/$id',
  path: '/api/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/import': typeof ApiImportRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/workers/process-batch': typeof ApiWorkersProcessBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/api/import': typeof ApiImportRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/workers/process-batch': typeof ApiWorkersProcessBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/api/import': typeof ApiImportRoute
  '/api/orders': typeof ApiOrdersRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/jobs/$id': typeof ApiJobsIdRoute
  '/api/workers/process-batch': typeof ApiWorkersProcessBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/api/import'
    | '/api/orders'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/workers/process-batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/api/import'
    | '/api/orders'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/workers/process-batch'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/api/import'
    | '/api/orders'
    | '/_protected/'
    | '/api/auth/$'
    | '/api/jobs/$id'
    | '/api/workers/process-batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiImportRoute: typeof ApiImportRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJobsIdRoute: typeof ApiJobsIdRoute
  ApiWorkersProcessBatchRoute: typeof ApiWorkersProcessBatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import': {
      id: '/api/import'
      path: '/api/import'
      fullPath: '/api/import'
      preLoaderRoute: typeof ApiImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/workers/process-batch': {
      id: '/api/workers/process-batch'
      path: '/api/workers/process-batch'
      fullPath: '/api/workers/process-batch'
      preLoaderRoute: typeof ApiWorkersProcessBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$id': {
      id: '/api/jobs/$id'
      path: '/api/jobs/$id'
      fullPath: '/api/jobs/$id'
      preLoaderRoute: typeof ApiJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiImportRoute: ApiImportRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJobsIdRoute: ApiJobsIdRoute,
  ApiWorkersProcessBatchRoute: ApiWorkersProcessBatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
